"""Study 5 of RESEARCH_LEDGER R062: robustness of the post hoc family intervals to the resampling scheme.

For every family comparison of the revision's Table S19 (timely PDR; estimand = unweighted mean over the
family's scenarios of the per-scenario mean paired difference), three summaries on the same runs:

  strat   the revision's stratified percentile bootstrap (seeds resampled within scenarios; scenarios
          fixed and equally weighted) -- identical to make_rev_numbers.py;
  2stage  a two-stage percentile bootstrap: scenarios resampled with replacement, then seeds within each
          drawn scenario; it treats the scenarios as a sample, so it answers a wider question and is
          expected to be wider;
  flip    a sign-flip randomisation test of "no difference": every seed-level paired difference has its
          sign flipped with probability 1/2, independently; two-sided p = share of |T*| >= |T|.

10,000 draws each (seed 20260930). No new runs. Writes paper/scripts/out/interval_robustness.json and
paper/tables/tab_s_interval_robustness.tex.
Usage (from the project root): python paper/scripts/interval_robustness.py
(imports FAM and PAIRS from paper/scripts/make_rev_numbers.py, read only)
"""

import json
import pathlib
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "analysis"))
sys.path.insert(0, str(ROOT / "paper" / "scripts"))
from q1_common import conditions, load, load_card, paired  # noqa: E402
from make_rev_numbers import FAM, PAIRS  # noqa: E402

NB, SEED = 10000, 20260930
LAB = {"AODV-STOCK": "stock AODV", "RREP-RESET": "fixed narrow start", "CARD": "CARD",
       "CLAF-AODV": "CLAF-AODV", "TAAODV": "TAAODV", "CARD-NO-EXEMPT": "radius-only",
       "CARD-NO-REACH": "exemption-only", "CARD-NO-CAUSE": "fixed hop-count start",
       "CARD-EXEMPT-ALL": "exempt-all", "CARD-CLAF": "CARD-CLAF"}
FAMNAME = {"C1": "Bottleneck", "C4": "Scaling", "S8": "Mobility"}


def summaries(per, rng):
    k = len(per)
    est = float(np.mean([d.mean() for d in per]))
    # stratified
    st = np.zeros(NB)
    for d in per:
        st += d[rng.integers(0, len(d), size=(NB, len(d)))].mean(axis=1)
    st /= k
    # two-stage
    ts = np.zeros(NB)
    pick = rng.integers(0, k, size=(NB, k))
    for j in range(k):
        for i in range(k):
            rows = np.where(pick[:, j] == i)[0]
            if rows.size:
                d = per[i]
                ts[rows] += d[rng.integers(0, len(d), size=(rows.size, len(d)))].mean(axis=1)
    ts /= k
    # sign flip
    fl = np.zeros(NB)
    for d in per:
        s = rng.choice([-1.0, 1.0], size=(NB, len(d)))
        fl += (s * d).mean(axis=1)
    fl /= k
    p = float((np.abs(fl) >= abs(est) - 1e-15).mean())
    zero = all(np.all(d == 0) for d in per)
    return {"est": est, "strat": [float(x) for x in np.percentile(st, [2.5, 97.5])],
            "two_stage": [float(x) for x in np.percentile(ts, [2.5, 97.5])],
            "p_flip": 1.0 if zero else p, "identical": zero, "scenarios": k}


def main():
    rng = np.random.default_rng(SEED)
    out = {}
    for tag, camp, _ in FAM:
        rows = load(camp)
        rows.update(load_card(camp))
        conds = [c for c in conditions(rows) if any(x == "CARD" and cc == c for (x, cc, _) in rows)]
        out[tag] = {}
        for a, b in PAIRS:
            per = [np.array(paired(rows, a, b, c), dtype=float) for c in conds]
            per = [d for d in per if len(d) >= 3]
            out[tag]["%s - %s" % (a, b)] = summaries(per, rng)
    (ROOT / "paper" / "scripts" / "out" / "interval_robustness.json").write_text(json.dumps(out, indent=1))

    def f(x):
        return ("%+.3f" % x).replace("-", "$-$")

    def cell(v):
        if v["identical"]:
            return "identical runs"
        s = "[%s, %s]" % (f(v["strat"][0]), f(v["strat"][1]))
        t = "[%s, %s]" % (f(v["two_stage"][0]), f(v["two_stage"][1]))
        p = "$<$0.001" if v["p_flip"] < 0.001 else "%.3f" % v["p_flip"]
        return "%s & %s & %s & %s" % (f(v["est"]), s, t, p)

    lines = ["%% generated by paper/scripts/interval_robustness.py -- do not edit",
             "\\begin{tabular}{@{}llrccr@{}}", "\\toprule",
             "Family & Comparison & Estimate & Stratified & Two-stage & $p_{\\mathrm{flip}}$ \\\\",
             "\\midrule"]
    for tag, _, _ in FAM:
        first = True
        for a, b in PAIRS:
            v = out[tag]["%s - %s" % (a, b)]
            c = cell(v)
            if v["identical"]:
                c = "\\multicolumn{4}{c}{identical runs}"
            lines.append("%s & %s minus %s & %s \\\\" % (FAMNAME[tag] if first else "", LAB[a], LAB[b], c))
            first = False
        lines.append("\\addlinespace")
    lines[-1] = "\\bottomrule"
    lines.append("\\end{tabular}")
    (ROOT / "paper" / "tables" / "tab_s_interval_robustness.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")
    # console summary: any disagreement in whether zero is excluded
    for tag in out:
        for k, v in out[tag].items():
            if v["identical"]:
                continue
            ex_s = v["strat"][0] > 0 or v["strat"][1] < 0
            ex_t = v["two_stage"][0] > 0 or v["two_stage"][1] < 0
            sig = v["p_flip"] < 0.05
            flag = "" if ex_s == ex_t == sig else "   <-- methods disagree"
            print("%s %-32s est %+.3f strat [%+.3f, %+.3f] 2stage [%+.3f, %+.3f] p %.4f%s" % (
                tag, k, v["est"], *v["strat"], *v["two_stage"], v["p_flip"], flag))
    return 0


if __name__ == "__main__":
    sys.exit(main())
