"""Revision: component and composition tables with family-level intervals.

Combines the original per-scenario counts (analysis_out/card_tables.json, unchanged analysis) with the
revision's family-level stratified-bootstrap intervals (paper/scripts/out/rev_numbers.json, post hoc).
Writes paper/tables/tab_components_rev.tex and tab_compose_rev.tex.
Usage (from the project root): python paper/scripts/make_rev_tables.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
TAB = ROOT / "paper" / "tables"
B = chr(92)
FAM = [("C1", "Bottleneck"), ("C4", "Scaling"), ("S8", "Mobility")]
R = json.loads((ROOT / "paper" / "scripts" / "out" / "rev_numbers.json").read_text())["family_ci"]
J = json.loads((ROOT / "analysis_out" / "card_tables.json").read_text())


def cell(tag, a, b, counts):
    v = R[tag]["%s - %s" % (a, b)]
    if abs(v["lo"]) < 1e-12 and abs(v["hi"]) < 1e-12 and abs(v["est"]) < 1e-12:
        return "identical runs"
    s = lambda x: ("%+.3f" % x).replace("+", "{+}").replace("-", "$-$")
    txt = "%s [%s, %s]" % (s(v["est"]), s(v["lo"]), s(v["hi"]))
    if counts:
        txt += " (%d/%d)" % counts
    return txt


def counts_minus(tag, v):
    s = J["families"][tag]["card_minus"].get(v)
    return (s["better"], s["worse"]) if s else None


def counts_compose(tag, ref):
    s = J["compose"][tag][ref]
    return (s["better"], s["worse"])


rows = [("CARD minus route-acquisition renewal", "CARD", "RREP-RESET"),
        ("CARD minus cause-blind reach", "CARD", "CARD-NO-CAUSE"),
        ("CARD minus every-break-exempt", "CARD", "CARD-EXEMPT-ALL"),
        ("CARD minus reach only", "CARD", "CARD-NO-EXEMPT"),
        ("CARD minus exemption only", "CARD", "CARD-NO-REACH")]
lines = ["%% generated by paper/scripts/make_rev_tables.py -- do not edit",
         B + "begin{tabular}{@{}lrrr@{}}", B + "toprule",
         "Comparison & " + " & ".join(n for _, n in FAM) + " " + B + B, B + "midrule"]
for lab, a, b in rows:
    lines.append("%s & %s %s%s" % (lab, " & ".join(cell(t, a, b, counts_minus(t, b)) for t, _ in FAM), B, B))
lines += [B + "bottomrule", B + "end{tabular}"]
(TAB / "tab_components_rev.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

rows = [("CARD-CLAF minus CLAF-AODV", "CLAF-AODV"), ("CARD-CLAF minus CARD", "CARD"),
        ("CARD-CLAF minus stock AODV", "AODV-STOCK")]
lines = ["%% generated by paper/scripts/make_rev_tables.py -- do not edit",
         B + "begin{tabular}{@{}lrrr@{}}", B + "toprule",
         "Comparison & " + " & ".join(n for _, n in FAM) + " " + B + B, B + "midrule"]
for lab, ref in rows:
    lines.append("%s & %s %s%s" % (lab, " & ".join(cell(t, "CARD-CLAF", ref, counts_compose(t, ref)) for t, _ in FAM), B, B))
lines += [B + "bottomrule", B + "end{tabular}"]
(TAB / "tab_compose_rev.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

# Fading table: the original generated table with the policy renamed (label text only; values unchanged).
fad = (TAB / "tab_card_fading.tex").read_text(encoding="utf-8")
fad = fad.replace("Route-level renewal", "Route-acquisition renewal").replace("route-level renewal",
                                                                          "route-acquisition renewal")
fad = fad.replace("%% generated by analysis/make_card_tables.py -- do not edit",
                  "%% relabelled copy of tab_card_fading.tex by paper/scripts/make_rev_tables.py -- do not edit")
(TAB / "tab_card_fading_rev.tex").write_text(fad, encoding="utf-8")
print("wrote tab_components_rev.tex, tab_compose_rev.tex, tab_card_fading_rev.tex")
