"""Regime table: each policy's timely-PDR difference from the better of the two fixed initial-radius rules.

The two fixed rules are route-acquisition renewal (every recovery starts from the smallest ring) and cause-blind reach
(every recovery starts from the last hop count), which share CARD's rationing and renewal event. In each family the
better rule is the one with the higher family estimate; the paired interval of their difference excludes zero in every
family. Every entry is an existing paired family estimate with its post hoc stratified-bootstrap interval:
  narrow rule minus wide rule   from scripts/out/sci_numbers.json (blind_minus_rr_<family>, sign reversed)
  CARD minus either rule        from scripts/out/rev_numbers.json (family_ci)
No run record is read and nothing is re-estimated.

Writes tables/tab_regime.tex and tables/regime_numbers.tex.
Usage (from the project root): python paper/scripts/regime_table.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
REV = ROOT / "paper"
FAM = [("C1", "Bottleneck"), ("C4", "Scaling"), ("S8", "Mobility")]
R = json.loads((REV / "scripts" / "out" / "rev_numbers.json").read_text())["family_ci"]
S = json.loads((REV / "scripts" / "out" / "sci_numbers.json").read_text())


def neg(v):
    return {"est": -v["est"], "lo": -v["hi"], "hi": -v["lo"]}


def fmt(x):
    return ("%+.3f" % x).replace("+", "{+}").replace("-", "$-$")


def cell(v):
    if max(abs(v["est"]), abs(v["lo"]), abs(v["hi"])) < 1e-12:
        return "0 (identical runs)"
    return "%s [%s, %s]" % (fmt(v["est"]), fmt(v["lo"]), fmt(v["hi"]))


rows = {"narrow": [], "wide": [], "card": []}
better = {}
for tag, _ in FAM:
    wide_minus_narrow = S["blind_minus_rr_%s" % tag]
    assert wide_minus_narrow["lo"] > 0 or wide_minus_narrow["hi"] < 0, tag  # the better rule is resolved
    if wide_minus_narrow["est"] < 0:  # narrow start is better
        better[tag] = "narrow"
        rows["narrow"].append(None)
        rows["wide"].append(wide_minus_narrow)
        rows["card"].append(R[tag]["CARD - RREP-RESET"])
    else:  # hop-count start is better
        better[tag] = "wide"
        rows["narrow"].append(neg(wide_minus_narrow))
        rows["wide"].append(None)
        rows["card"].append(R[tag]["CARD - CARD-NO-CAUSE"])

worst = {k: min(0.0 if v is None else v["est"] for v in vals) for k, vals in rows.items()}

lines = [
    "% generated by paper/scripts/regime_table.py from existing family estimates; do not edit",
    r"\begin{tabular}{@{}llll r@{}}",
    r"\toprule",
    r"Policy (initial radius) & Bottleneck & Scaling & Mobility & Worst case \\",
    r"\midrule",
]
label = {"narrow": "Fixed narrow start (route-acquisition renewal)",
         "wide": "Fixed hop-count start (cause-blind reach)",
         "card": "Cause-conditioned start (CARD)"}
for k in ["narrow", "wide", "card"]:
    cells = ["better rule" if v is None else cell(v) for v in rows[k]]
    w = worst[k]
    wtxt = "0" if abs(w) < 5e-4 else fmt(w)
    lines.append("%s & %s & %s \\\\" % (label[k], " & ".join(cells), wtxt))
lines += [r"\bottomrule", r"\end{tabular}", ""]
(REV / "tables" / "tab_regime.tex").write_text("\n".join(lines), encoding="utf-8")

B = chr(92)
mac = ["% generated by paper/scripts/regime_table.py; do not edit"]
for k, name in [("narrow", "Narrow"), ("wide", "Wide"), ("card", "Card")]:
    mac.append("%snewcommand{%sRegWorst%s}{%.3f}" % (B, B, name, -worst[k]))
    mac.append("%snewcommand{%sRegWorst%sPp}{%.1f}" % (B, B, name, -100 * worst[k]))
# losses of each fixed rule in the families where the other rule is better (percentage points)
losses = [-v["est"] for k in ("narrow", "wide") for v in rows[k] if v is not None]
mac.append("%snewcommand{%sRegMinLossPp}{%.1f}" % (B, B, 100 * min(losses)))
mac.append("%snewcommand{%sRegMaxLossPp}{%.1f}" % (B, B, 100 * max(losses)))
# scenarios in which the hop-count start's scenario mean exceeded the narrow start's
for tag, name in [("C1", "Cone"), ("C4", "Cfour"), ("S8", "Seight")]:
    v = S["blind_minus_rr_%s" % tag]
    mac.append("%snewcommand{%sReg%sWidePos}{%d}" % (B, B, name, v["positive_scenario_means"]))
    mac.append("%snewcommand{%sReg%sN}{%d}" % (B, B, name, v["scenarios"]))
(REV / "tables" / "regime_numbers.tex").write_text("\n".join(mac) + "\n", encoding="utf-8")
print("better rule per family:", better)
print("worst-case difference from the better rule:", {k: round(v, 4) for k, v in worst.items()})
