"""Apply the manuscript's policy names to the renewal-study tables generated by the original analysis pipeline.

analysis/make_q1_tables.py writes these tables with its own display names (Route-level, Service-level, Clock). The
manuscript calls the same policies acquisition renewal, confirmation renewal and clock renewal. This script rewrites
only those display labels, in place; values are untouched. It is idempotent, so it can be run after every
regeneration of the tables.
Usage (from the project root): python paper/scripts/relabel_tables.py
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
TAB = ROOT / "paper" / "tables"
FILES = ["tab_ordering.tex", "tab_recovery.tex", "tab_frequency.tex", "tab_mechanism.tex", "tab_ablation.tex",
         "tab_ablation_full.tex", "tab_s_scr2.tex", "tab_card_percond.tex"]
# Order matters: longer labels first. No replacement text contains its own source text, so repeated runs are no-ops.
MAP = [("Service-level + backoff", "Confirmation renewal + backoff"),
       ("Service-level, no gate", "Confirmation renewal, no gate"),
       ("Service-level", "Confirmation renewal"),
       ("service-level", "confirmation renewal"),
       ("$\\Delta$ vs route-level", "$\\Delta$ vs fixed narrow start"),
       ("Route-level", "Acquisition renewal"),
       ("\nClock &", "\nClock renewal &"),
       ("& Clock &", "& Clock renewal &"),
       ("$\\Delta$ vs SCR", "$\\Delta$ vs confirmation renewal")]

for name in FILES:
    p = TAB / name
    if not p.exists():  # not generated yet
        continue
    t = p.read_text(encoding="utf-8")
    for a, b in MAP:
        t = t.replace(a, b)
    p.write_text(t, encoding="utf-8")
print("relabelled", ", ".join(FILES))
