"""Numbers added in the scientific revision, all computed from the stored run records.

1. Composition hypothesis H2 (RESEARCH_LEDGER R060): CARD-CLAF minus CARD over the six scaling scenarios with
   90 or more nodes (S7-S12) -- the scenario set the hypothesis names. Estimate = unweighted mean over those
   scenarios of the per-scenario mean paired difference in timely PDR; POST HOC 95% stratified percentile
   bootstrap interval (seeds resampled within scenarios, scenarios fixed and equally weighted, 10,000
   resamples, seed 20260930). The earlier revision reported the estimate without an interval.
2. Implied differences used in the argument: cause-blind reach minus route-acquisition renewal per family
   (always-wide versus always-narrow initial radius under the same rationing), with the same bootstrap.
3. Check that the tabulated pooled timely PDR is the mean of run-level ratios (on-time packets / generated
   packets of each run), and report the ratio of packet totals alongside it for the four main policies.

Reads checkpoints/ (read only) through analysis/q1_common.py. Writes
paper/tables/sci_numbers.tex and paper/scripts/out/sci_numbers.json.
Usage (from the project root): python paper/scripts/sci_numbers.py
"""

import json
import pathlib
import statistics as st
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "analysis"))
from q1_common import conditions, load, load_card, paired  # noqa: E402

NBOOT, SEED = 10000, 20260930
OUT_TEX = ROOT / "paper" / "tables" / "sci_numbers.tex"
OUT_JSON = ROOT / "paper" / "scripts" / "out" / "sci_numbers.json"


def family(rows, conds, a, b, rng):
    per = [np.array(paired(rows, a, b, c), dtype=float) for c in conds]
    per = [d for d in per if len(d) >= 3]
    est = float(np.mean([d.mean() for d in per]))
    boots = np.zeros(NBOOT)
    for d in per:
        boots += d[rng.integers(0, len(d), size=(NBOOT, len(d)))].mean(axis=1)
    boots /= len(per)
    lo, hi = np.percentile(boots, [2.5, 97.5])
    means = [float(d.mean()) for d in per]
    return {"est": est, "lo": float(lo), "hi": float(hi), "scenarios": len(per),
            "positive_scenario_means": sum(m > 0 for m in means)}


def s3(x):
    return "$%+.3f$" % x


def main():
    rng = np.random.default_rng(SEED)
    M, J = {}, {}
    # 1. H2 over the six large scaling scenarios.
    rows = load("c4_scaling")
    rows.update(load_card("c4_scaling"))
    conds = [c for c in conditions(rows) if any(x == "CARD" and cc == c for (x, cc, _) in rows)]
    large = [c for c in conds if float(c[0]) >= 90]
    assert len(large) == 6, large
    h2 = family(rows, large, "CARD-CLAF", "CARD", rng)
    J["H2_large_scaling"] = dict(h2, conditions=[list(c) for c in large])
    M["SciHtwoD"] = s3(h2["est"])
    M["SciHtwoCI"] = "[%s, %s]" % (s3(h2["lo"]), s3(h2["hi"]))
    M["SciHtwoPos"] = str(h2["positive_scenario_means"])
    # 2. Always-wide (cause-blind reach) minus always-narrow (route-acquisition renewal).
    for tag, camp, T in (("C1", "c1_outage", "Cone"), ("C4", "c4_scaling", "Cfour"),
                         ("S8", "stage8_campaign", "Seight")):
        r = load(camp)
        r.update(load_card(camp))
        cs = [c for c in conditions(r) if any(x == "CARD" and cc == c for (x, cc, _) in r)]
        v = family(r, cs, "CARD-NO-CAUSE", "RREP-RESET", rng)
        J["blind_minus_rr_" + tag] = v
        M["Sci%sBlindRRD" % T] = s3(v["est"])
        M["Sci%sBlindRRCI" % T] = "[%s, %s]" % (s3(v["lo"]), s3(v["hi"]))
        # 3. Mean of run ratios versus ratio of totals.
        for arm in ("AODV-STOCK", "RREP-RESET", "CARD", "CLAF-AODV"):
            kv = [x for (a, c, _), x in r.items() if a == arm and c in cs]
            run_mean = st.mean(float(x["ontime_true"]) / float(x["generated"]) for x in kv)
            tot = sum(float(x["ontime_true"]) for x in kv) / sum(float(x["generated"]) for x in kv)
            J.setdefault("pooled_pdr_" + tag, {})[arm] = {"mean_of_run_ratios": run_mean,
                                                          "ratio_of_totals": tot, "runs": len(kv)}
    ps = J["pooled_pdr_S8"]["AODV-STOCK"]
    M["SciPdrSeightStockRuns"] = "%.3f" % ps["mean_of_run_ratios"]
    M["SciPdrSeightStockTot"] = "%.3f" % ps["ratio_of_totals"]
    lines = ["%% generated by paper/scripts/sci_numbers.py -- do not edit"]
    lines += ["\\newcommand{\\%s}{%s}" % (k, v) for k, v in sorted(M.items())]
    OUT_TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(J, indent=1))
    for k, v in sorted(M.items()):
        print("%-22s %s" % (k, v))
    for tag in ("C1", "C4", "S8"):
        for arm, v in J["pooled_pdr_" + tag].items():
            print("%s %-11s mean of run ratios %.4f  ratio of totals %.4f" % (
                tag, arm, v["mean_of_run_ratios"], v["ratio_of_totals"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
