"""Generate the CARD tables and prose macros from the run records (R053-R055).

Writes
  paper/tables/tab_card_main.tex        CARD against the baselines, per family
  paper/tables/tab_card_ablation.tex    which part of CARD does the work
  paper/tables/tab_card_classifier.tex  break verdicts against true geometry
  paper/tables/tab_card_search.tex      searches and relays per search, every scenario (R059)
  paper/tables/tab_card_compose.tex     preregistered CARD-CLAF composition test (R060)
  paper/tables/tab_card_fading.tex      preregistered fading supplement (R056)
  paper/tables/card_numbers.tex         one macro per number quoted in the prose
  analysis_out/card_tables.json              every number, for checking prose against tables

CARD runs come from checkpoints/card_campaign (fork_rev 7); every baseline comes
from the published campaigns at the same conditions and seeds (fork_rev 5). The
pairing is valid because rev 7 reproduces rev 5 exactly for every pre-CARD mode
and node trajectories agree across algorithms to within 4e-8 m (R055).

Run:  python analysis/make_card_tables.py
"""

import csv
import json
import math
import statistics as st

from q1_common import (ROOT, RUNS, boot, conditions, load, load_card, mean_of, paired, sign_p,
                       val)

TAB = ROOT / "paper" / "tables"
OUT = ROOT / "analysis_out" / "card_tables.json"
B = chr(92)
NL = chr(10)

FAMILIES = [("C1", "c1_outage", "Bottleneck"), ("C4", "c4_scaling", "Scaling"),
            ("S8", "stage8_campaign", "Mobility")]
TAG = {"C1": "Cone", "C4": "Cfour", "S8": "Seight"}
# Display names. Implementation labels stay the keys in the run records.
LABEL = {"AODV-STOCK": "Stock AODV", "RREP-RESET": "Route-level renewal", "CARD": "CARD",
         "CARD-NO-CAUSE": "Cause-blind reach", "CARD-EXEMPT-ALL": "Every break exempt",
         "CARD-NO-EXEMPT": "Cause-aware reach only", "CARD-NO-REACH": "Cause-aware exemption only",
         "CLAF-AODV": "CLAF-AODV \\cite{safari2023claf}", "TAAODV": "TAAODV \\cite{li2025taaodv}"}
ARMTAG = {"AODV-STOCK": "Stock", "RREP-RESET": "RR", "CARD": "Card", "CARD-NO-CAUSE": "Blind",
          "CARD-EXEMPT-ALL": "Exall", "CARD-NO-EXEMPT": "Noex", "CARD-NO-REACH": "Noreach",
          "CLAF-AODV": "Claf", "TAAODV": "Taa"}
MAIN = ["AODV-STOCK", "CLAF-AODV", "TAAODV", "RREP-RESET", "CARD", "CARD-NO-CAUSE",
        "CARD-EXEMPT-ALL"]
VARIANTS = ["RREP-RESET", "CARD-NO-CAUSE", "CARD-EXEMPT-ALL", "CARD-NO-EXEMPT", "CARD-NO-REACH"]
BASELINES = ["CLAF-AODV", "TAAODV"]
RANGE_M, HORIZON_S = 141.0, 1.0  # link cliff (stage2 sweep) and hello interval; see card_classifier.py


def write(name, lines):
    TAB.mkdir(parents=True, exist_ok=True)
    (TAB / name).write_text("%% generated by analysis/make_card_tables.py -- do not edit" + NL
                            + NL.join(lines) + NL, encoding="utf-8")


def f3(x):
    return ("$%+.3f$" % x).replace("+", "{+}") if x is not None else "--"


def rows_for(camp):
    rows = load(camp)
    rows.update(load_card(camp))
    return rows


def family_stats(rows, conds, arm, ref):
    """Per-condition paired differences of arm minus ref, and their summary."""
    per = {}
    for c in conds:
        d = paired(rows, arm, ref, c)
        if len(d) < 3:
            continue
        db = paired(rows, arm, ref, c, "bytes_per_pkt")
        rb = [val(rows[(ref, c, s)], "bytes_per_pkt") for (a, cc, s) in rows
              if a == ref and cc == c]
        lo, hi = boot(d)
        per["/".join(str(x) for x in c)] = {
            "n": len(d), "mean": st.mean(d), "lo": lo, "hi": hi, "p_sign": sign_p(d),
            "bytes_mean": st.mean(db),
            "bytes_rel_pct": 100 * st.mean(db) / st.mean(rb) if rb and st.mean(rb) else None}
    if not per:
        return None
    means = [v["mean"] for v in per.values()]
    return {"conditions": len(per), "mean_of_means": st.mean(means),
            "min": min(means), "max": max(means),
            "better": sum(v["lo"] > 0 for v in per.values()),
            "worse": sum(v["hi"] < 0 for v in per.values()),
            "bytes_rel_pct_mean": st.mean(v["bytes_rel_pct"] for v in per.values()
                                          if v["bytes_rel_pct"] is not None),
            "per_condition": per}


SEARCH_ARMS = ["AODV-STOCK", "CLAF-AODV", "TAAODV", "CARD", "CARD-CLAF"]


def search_counts(rows, c, arm):
    """Mean source searches per 1000 generated packets and relayed copies per search."""
    per_k, per_s = [], []
    for (a, cc, s), kv in rows.items():
        if a != arm or cc != c:
            continue
        try:
            src = float(kv["source_rreq_originated"])
            rel = float(kv["ctrl_rreq_relayed"])
            gen = float(kv["generated"])
        except (KeyError, ValueError):
            continue
        per_k.append(1000.0 * src / gen)
        per_s.append(rel / src if src else 0.0)
    return (st.mean(per_k), st.mean(per_s), len(per_k)) if per_k else (None, None, 0)


def write_search_table(fam_rows, J):
    lines = [B + "begin{tabular}{@{}ll" + "r" * (2 * len(SEARCH_ARMS)) + "@{}}", B + "toprule",
             B + "multicolumn{2}{l}{} & " + B + "multicolumn{%d}{c}{requests originated per 1000 packets} & " % len(SEARCH_ARMS)
             + B + "multicolumn{%d}{c}{relayed copies per request} " % len(SEARCH_ARMS) + B + B,
             "Family & Scenario & " + " & ".join(["Stock", "CLAF", "TAA", "CARD", "C+C"] * 2) + " " + B + B,
             B + "midrule"]
    J["search"] = {}
    for tag, _, name in FAMILIES:
        if tag not in fam_rows:
            continue
        rows, conds = fam_rows[tag]
        first = True
        for c in conds:
            vals = {a: search_counts(rows, c, a) for a in SEARCH_ARMS}
            key = "/".join(str(x) for x in c)
            J["search"].setdefault(tag, {})[key] = vals
            cells = [("%.1f" % vals[a][0]) if vals[a][0] is not None else "--" for a in SEARCH_ARMS]
            cells += [("%.1f" % vals[a][1]) if vals[a][1] is not None else "--" for a in SEARCH_ARMS]
            lines.append("%s & %s & %s %s%s" % (name if first else "", key.replace("_", r"\_"),
                                                 " & ".join(cells), B, B))
            first = False
        lines.append(B + "addlinespace")
    if lines[-1] == B + "addlinespace":
        lines.pop()
    lines += [B + "bottomrule", B + "end{tabular}"]
    write("tab_card_search.tex", lines)


COMPOSE = "CARD-CLAF"
COMPOSE_REFS = [("CLAF-AODV", "Claf", "CLAF-AODV"), ("CARD", "Card", "CARD"),
                ("AODV-STOCK", "Stock", "stock AODV")]


def compose_stats(fam_rows):
    """R060 preregistered comparisons: CARD-CLAF minus CLAF-AODV, CARD and stock, per family,
    plus the H2 subset (scaling scenarios with >= 90 nodes) and the H3 count (scenarios in which
    CARD-CLAF is significantly below CARD or below CLAF-AODV)."""
    out = {}
    for tag, _, _ in FAMILIES:
        if tag not in fam_rows:
            continue
        rows, conds = fam_rows[tag]
        if not any(a == COMPOSE for (a, _, _) in rows):
            continue
        F = {ref: family_stats(rows, conds, COMPOSE, ref) for ref, _, _ in COMPOSE_REFS}
        below = set()
        for ref in ("CARD", "CLAF-AODV"):
            if F[ref]:
                below |= {k for k, v in F[ref]["per_condition"].items() if v["hi"] < 0}
        F["below_best"] = sorted(below)
        if tag == "C4" and F["CARD"]:
            large = [v["mean"] for k, v in F["CARD"]["per_condition"].items()
                     if int(k.split("/")[0]) >= 90]
            F["large_vs_card_mean"] = st.mean(large) if large else None
            F["large_n"] = len(large)
        out[tag] = F
    return out


def write_compose_table(C):
    lines = [B + "begin{tabular}{@{}l" + "r" * len(COMPOSE_REFS) + "@{}}", B + "toprule",
             "CARD-CLAF minus & " + " & ".join(n for _, _, n in COMPOSE_REFS) + " " + B + B,
             B + "midrule"]
    for tag, _, name in FAMILIES:
        F = C.get(tag)
        if not F:
            continue
        cells = []
        for ref, _, _ in COMPOSE_REFS:
            x = F.get(ref)
            cells.append("%s (%d/%d)" % (f3(x["mean_of_means"]), x["better"], x["worse"]) if x else "--")
        lines.append("%s & %s %s%s" % (name, " & ".join(cells), B, B))
    lines += [B + "bottomrule", B + "end{tabular}"]
    write("tab_card_compose.tex", lines)


FADE_ARMS = ["AODV-STOCK", "RREP-RESET", "CARD", "CARD-NO-CAUSE"]
FADE_PAIRS = [("CARD", "AODV-STOCK", "CardVsStock", "CARD minus stock AODV"),
              ("CARD", "RREP-RESET", "CardVsRR", "CARD minus route-level renewal"),
              ("CARD", "CARD-NO-CAUSE", "CardVsBlind", "CARD minus cause-blind reach"),
              ("RREP-RESET", "AODV-STOCK", "RRVsStock", "route-level renewal minus stock AODV")]


def load_fading():
    """R056 fading runs (checkpoints/card_fading, fork_rev 7), keyed like load_card rows."""
    out = {}
    base = RUNS / "card_fading"
    if not base.exists():
        return out
    for e in base.iterdir():
        s_ = e / "out_summary.csv"
        if not (e.is_dir() and e.name.startswith("f_") and s_.exists() and (e / "DONE.json").exists()):
            continue
        kv = {}
        for line in s_.read_text(errors="replace").splitlines()[1:]:
            k, _, v = line.partition(",")
            kv[k.strip()] = v.strip().strip('"')
        if "fork_rev=7" not in kv.get("effective_parameters", "") or kv.get("c3_fading") != "1":
            continue
        cond = (kv.get("speed_mps"), kv.get("rate_pps"), kv.get("num_flows"))
        out[(kv["algorithm"], cond, kv["rng_run"])] = kv
    return out


def fading_stats():
    rows = load_fading()
    if not rows:
        return None
    conds = conditions(rows)
    F = {"conditions": [list(c) for c in conds], "runs": len(rows), "cells": {}}
    for c in conds:
        cell = {"timely": {}, "pairs": {}}
        for a in FADE_ARMS:
            t, n = pooled(rows, [c], a, "timely")
            b, _ = pooled(rows, [c], a, "bytes_per_pkt")
            cell["timely"][a] = {"timely": t, "bytes_per_pkt": b, "runs": n}
        for a, ref, tag, _ in FADE_PAIRS:
            x = family_stats(rows, [c], a, ref)
            if x:
                v = next(iter(x["per_condition"].values()))
                cell["pairs"][tag] = {"mean": v["mean"], "lo": v["lo"], "hi": v["hi"], "n": v["n"],
                                      "bytes_rel_pct": v["bytes_rel_pct"]}
        F["cells"]["/".join(str(x) for x in c)] = cell
    return F


def write_fading_table(F):
    lines = [B + "begin{tabular}{@{}l" + "r" * len(F["cells"]) + "@{}}", B + "toprule",
             "Speed (m/s) & " + " & ".join("%g" % float(k.split("/")[0]) for k in F["cells"])
             + " " + B + B, B + "midrule"]
    for a in FADE_ARMS:
        lines.append("PDR$_" + B + "mathrm{t}$, %s & %s %s%s" % (
            LABEL[a], " & ".join("%.3f" % F["cells"][k]["timely"][a]["timely"] for k in F["cells"]), B, B))
    lines.append(B + "addlinespace")
    for _, _, tag, name in FADE_PAIRS:
        cells = []
        for k in F["cells"]:
            v = F["cells"][k]["pairs"].get(tag)
            cells.append("%s [%s, %s]" % (f3(v["mean"]), f3(v["lo"]), f3(v["hi"])) if v else "--")
        lines.append("%s & %s %s%s" % (name[0].upper() + name[1:], " & ".join(cells), B, B))
    lines += [B + "bottomrule", B + "end{tabular}"]
    write("tab_card_fading.tex", lines)


def pooled(rows, conds, arm, m):
    v = [val(kv, m) for (a, c, s), kv in rows.items() if a == arm and c in conds]
    return (st.mean(v), len(v)) if v else (None, 0)


def classifier(fam_prefix):
    """Verdicts of the CARD arm's break logs against geometry, one family."""
    c = {"tp": 0, "fp": 0, "fn": 0, "tn": 0, "unknown": 0, "runs": 0}
    base = RUNS / "card_campaign"
    if not base.exists():
        return c
    for d in base.iterdir():
        if not d.is_dir() or not (d / "DONE.json").exists():
            continue
        name = d.name
        fam = "c1_" if name.startswith("c1_") else ("c4_" if name.startswith("c4_") else "c_")
        if fam != fam_prefix or "_CARD_s" not in name:
            continue
        f = d / "out_card_breaks.csv"
        if not f.exists():
            continue
        c["runs"] += 1
        with open(f, newline="") as fh:
            for r in csv.DictReader(fh):
                try:
                    dist, vr = float(r["dist_m"]), float(r["radial_mps"])
                except ValueError:
                    continue
                if math.isnan(dist):
                    continue
                departed = dist > RANGE_M or dist + max(vr, 0.0) * HORIZON_S > RANGE_M
                v = r["verdict"]
                if v == "2":
                    c["unknown"] += 1
                elif v == "1":
                    c["tp" if departed else "fp"] += 1
                else:
                    c["fn" if departed else "tn"] += 1
    n = c["tp"] + c["fp"] + c["fn"] + c["tn"]
    c["breaks"] = n + c["unknown"]
    c["departed_share"] = (c["tp"] + c["fn"]) / n if n else None
    c["precision_topology"] = c["tp"] / (c["tp"] + c["fp"]) if c["tp"] + c["fp"] else None
    c["recall_topology"] = c["tp"] / (c["tp"] + c["fn"]) if c["tp"] + c["fn"] else None
    c["precision_transient"] = c["tn"] / (c["tn"] + c["fn"]) if c["tn"] + c["fn"] else None
    c["accuracy"] = (c["tp"] + c["tn"]) / n if n else None
    return c


def main():
    J = {"families": {}, "classifier": {}, "runs": {}}
    main_lines = [B + "begin{tabular}{@{}llrrrrr@{}}", B + "toprule",
                  "Family & Policy & PDR$_\\mathrm{t}$ & $\\Delta$ vs stock & better/worse & B/pkt"
                  " & $\\Delta$B \\\\", B + "midrule"]
    abl_lines = [B + "begin{tabular}{@{}lrrrrr@{}}", B + "toprule",
                 "CARD minus & " + " & ".join(n for _, _, n in FAMILIES) + " \\\\",
                 B + "midrule"]
    abl = {}
    fam_rows = {}
    for tag, camp, name in FAMILIES:
        rows = rows_for(camp)
        conds = [c for c in conditions(rows)
                 if any(a == "CARD" and cc == c for (a, cc, _) in rows)]
        if not conds:
            print("%s: no CARD runs yet" % name)
            continue
        fam_rows[tag] = (rows, conds)
        F = {"conditions": len(conds), "arms": {}}
        for arm in MAIN + ["CARD-NO-EXEMPT", "CARD-NO-REACH"]:
            t, n = pooled(rows, conds, arm, "timely")
            b, _ = pooled(rows, conds, arm, "bytes_per_pkt")
            if t is None:
                continue
            A = {"timely": t, "bytes_per_pkt": b, "runs": n}
            if arm != "AODV-STOCK":
                A["vs_stock"] = family_stats(rows, conds, arm, "AODV-STOCK")
            if arm != "RREP-RESET" and arm != "AODV-STOCK":
                A["vs_rr"] = family_stats(rows, conds, arm, "RREP-RESET")
            F["arms"][arm] = A
        # CARD minus each variant: which component carries the result
        F["card_minus"] = {v: family_stats(rows, conds, "CARD", v) for v in VARIANTS + BASELINES
                           if v in F["arms"]}
        J["families"][tag] = F
        first = True
        for arm in MAIN:
            if arm not in F["arms"]:
                continue
            A = F["arms"][arm]
            vs = A.get("vs_stock")
            main_lines.append("%s & %s & %.3f & %s & %s & %.1f & %s \\\\" % (
                ("%s (%d)" % (name, len(conds))) if first else "", LABEL[arm], A["timely"],
                f3(vs["mean_of_means"]) if vs else "--",
                ("%d/%d" % (vs["better"], vs["worse"])) if vs else "--",
                A["bytes_per_pkt"],
                ("%+.0f\\%%" % vs["bytes_rel_pct_mean"]).replace("+", "{+}") if vs else "--"))
            first = False
        main_lines.append(B + "addlinespace")
        for v, s in F["card_minus"].items():
            if s:
                abl.setdefault(v, {})[tag] = s
        J["classifier"][tag] = classifier({"C1": "c1_", "C4": "c4_", "S8": "c_"}[tag])
        J["runs"][tag] = sum(1 for (a, c, s) in rows if a in F["arms"] and c in conds)
    if main_lines[-1] == B + "addlinespace":
        main_lines.pop()
    main_lines += [B + "bottomrule", B + "end{tabular}"]
    write("tab_card_main.tex", main_lines)

    for v in VARIANTS:
        if v not in abl:
            continue
        cells = []
        for tag, _, _ in FAMILIES:
            s = abl[v].get(tag)
            cells.append("%s (%d/%d)" % (f3(s["mean_of_means"]), s["better"], s["worse"])
                         if s else "--")
        abl_lines.append("%s & %s \\\\" % (LABEL[v], " & ".join(cells)))
    abl_lines += [B + "bottomrule", B + "end{tabular}"]
    write("tab_card_ablation.tex", abl_lines)

    cl_lines = [B + "begin{tabular}{@{}lrrrrrr@{}}", B + "toprule",
                "Family & breaks & departures & precision (topology) & recall (departures) & "
                "precision (transient) & accuracy \\\\", B + "midrule"]
    for tag, _, name in FAMILIES:
        c = J["classifier"].get(tag)
        if not c or not c["breaks"]:
            continue
        fmt = lambda x: "%.3f" % x if x is not None else "--"
        cl_lines.append("%s & %s & %s & %s & %s & %s & %s \\\\" % (
            name, "{:,}".format(c["breaks"]).replace(",", "{,}"),
            ("%.1f\\%%" % (100 * c["departed_share"])) if c["departed_share"] is not None else "--",
            fmt(c["precision_topology"]), fmt(c["recall_topology"]),
            fmt(c["precision_transient"]), fmt(c["accuracy"])))
    cl_lines += [B + "bottomrule", B + "end{tabular}"]
    write("tab_card_classifier.tex", cl_lines)

    # Supplementary: every scenario, CARD against stock AODV and route-level renewal.
    pc = [B + "begin{tabular}{@{}llrrrr@{}}", B + "toprule",
          "Family & Scenario & $\\Delta$ vs stock & 95\\% CI & $\\Delta$ vs route-level & 95\\% CI \\\\",
          B + "midrule"]
    for tag, _, name in FAMILIES:
        F = J["families"].get(tag)
        if not F or "CARD" not in F["arms"]:
            continue
        vs = F["arms"]["CARD"].get("vs_stock") or {"per_condition": {}}
        vr = F["arms"]["CARD"].get("vs_rr") or {"per_condition": {}}
        first = True
        for key in vs["per_condition"]:
            a, r = vs["per_condition"][key], vr["per_condition"].get(key)
            pc.append("%s & %s & %s & [%s, %s] & %s & %s \\\\" % (
                name if first else "", key.replace("_", r"\_"), f3(a["mean"]), f3(a["lo"]),
                f3(a["hi"]), f3(r["mean"]) if r else "--",
                ("[%s, %s]" % (f3(r["lo"]), f3(r["hi"]))) if r else "--"))
            first = False
        pc.append(B + "addlinespace")
    if pc[-1] == B + "addlinespace":
        pc.pop()
    pc += [B + "bottomrule", B + "end{tabular}"]
    write("tab_card_percond.tex", pc)
    write_search_table(fam_rows, J)
    # R061: why the exemption adds no delivery -- denials for lack of allowance
    # with and without it, and the requests actually sent.
    J["exempt"] = {}
    for tag in ("C4", "S8"):
        if tag not in fam_rows:
            continue
        rows_, conds_ = fam_rows[tag]
        m = {}
        for a in ("CARD", "CARD-NO-EXEMPT"):
            dn = [float(kv["deny_no_allowance"]) for (aa, c, _), kv in rows_.items()
                  if aa == a and c in conds_ and "deny_no_allowance" in kv]
            rq = [float(kv["source_rreq_originated"]) for (aa, c, _), kv in rows_.items()
                  if aa == a and c in conds_]
            m[a] = (st.mean(dn) if dn else None, st.mean(rq) if rq else None)
        if all(v[0] and v[1] for v in m.values()):
            J["exempt"][tag] = {"deny_ratio": m["CARD-NO-EXEMPT"][0] / m["CARD"][0],
                                "req_pct": 100.0 * (m["CARD-NO-EXEMPT"][1] / m["CARD"][1] - 1.0)}
    J["fading"] = fading_stats()
    if J["fading"]:
        write_fading_table(J["fading"])
    J["compose"] = compose_stats(fam_rows)
    if J["compose"]:
        write_compose_table(J["compose"])

    write_numbers(J)
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(J, indent=1, default=float))
    print("wrote tab_card_main.tex, tab_card_ablation.tex, tab_card_classifier.tex, %s" % OUT.name)


def write_numbers(J):
    M = {}

    def put(k, v):
        M[k] = v

    def dec(x, n=3):
        return ("%." + str(n) + "f") % x

    def pct(x):
        return "%.0f" % abs(x)

    for tag, F in J["families"].items():
        T = TAG[tag]
        put("%sNconds" % T, str(F["conditions"]))
        for arm, A in F["arms"].items():
            a = ARMTAG[arm]
            put("Card%s%sT" % (T, a), dec(A["timely"]))
            put("Card%s%sB" % (T, a), dec(A["bytes_per_pkt"], 1))
            for ref, rt in (("vs_stock", "VsStock"), ("vs_rr", "VsRR")):
                s = A.get(ref)
                if not s:
                    continue
                put("Card%s%s%sD" % (T, a, rt), ("$%+.3f$" % s["mean_of_means"]))
                put("Card%s%s%sDabs" % (T, a, rt), dec(abs(s["mean_of_means"])))
                put("Card%s%s%sBetter" % (T, a, rt), str(s["better"]))
                put("Card%s%s%sWorse" % (T, a, rt), str(s["worse"]))
                put("Card%s%s%sMin" % (T, a, rt), ("$%+.3f$" % s["min"]))
                put("Card%s%s%sMax" % (T, a, rt), ("$%+.3f$" % s["max"]))
                put("Card%s%s%sBpct" % (T, a, rt), pct(s["bytes_rel_pct_mean"]))
                put("Card%s%s%sBsign" % (T, a, rt),
                    "fewer" if s["bytes_rel_pct_mean"] < 0 else "more")
        for v, s in F.get("card_minus", {}).items():
            if s:
                put("Card%sMinus%sD" % (T, ARMTAG[v]), ("$%+.3f$" % s["mean_of_means"]))
                put("Card%sMinus%sDabs" % (T, ARMTAG[v]), dec(abs(s["mean_of_means"])))
                put("Card%sMinus%sBetter" % (T, ARMTAG[v]), str(s["better"]))
                put("Card%sMinus%sWorse" % (T, ARMTAG[v]), str(s["worse"]))
                # R059: CARD's control bytes relative to the variant or baseline.
                put("Card%sMinus%sBpct" % (T, ARMTAG[v]), pct(s["bytes_rel_pct_mean"]))
                put("Card%sMinus%sBsign" % (T, ARMTAG[v]),
                    "fewer" if s["bytes_rel_pct_mean"] < 0 else "more")
    for tag, e in J.get("exempt", {}).items():
        put("Card%sNoexDenyRatio" % TAG[tag], "%.1f" % e["deny_ratio"])
        put("Card%sNoexReqPct" % TAG[tag], "%.0f" % abs(e["req_pct"]))
        put("Card%sNoexReqSign" % TAG[tag], "fewer" if e["req_pct"] < 0 else "more")
    FD = J.get("fading")
    if FD:
        for k, cell in FD["cells"].items():
            sp = {5.0: "Five", 10.0: "Ten"}[float(k.split("/")[0])]
            for tag, v in cell["pairs"].items():
                put("CardFade%s%sD" % (sp, tag), ("$%+.3f$" % v["mean"]))
                put("CardFade%s%sDabs" % (sp, tag), dec(abs(v["mean"])))
                put("CardFade%s%sLo" % (sp, tag), ("$%+.3f$" % v["lo"]))
                put("CardFade%s%sHi" % (sp, tag), ("$%+.3f$" % v["hi"]))
        fc = ROOT / "analysis_out" / "card_classifier_card_fading.json"
        if fc.exists():
            c = json.loads(fc.read_text()).get("mobility", {})
            for key, name in (("precision_topology", "PrecTopo"), ("recall_topology", "RecTopo"),
                              ("precision_transient", "PrecTrans"), ("accuracy_classified", "Acc")):
                if c.get(key) is not None:
                    put("CardFade%s" % name, dec(c[key], 2))
            if c.get("departure_share") is not None:
                put("CardFadeDepartedPct", "%.1f" % (100 * c["departure_share"]))
    for tag, F in J.get("compose", {}).items():
        T = TAG[tag]
        for ref, rt, _ in COMPOSE_REFS:
            x = F.get(ref)
            if not x:
                continue
            put("Card%sComposeVs%sD" % (T, rt), ("$%+.3f$" % x["mean_of_means"]))
            put("Card%sComposeVs%sDabs" % (T, rt), dec(abs(x["mean_of_means"])))
            put("Card%sComposeVs%sBetter" % (T, rt), str(x["better"]))
            put("Card%sComposeVs%sWorse" % (T, rt), str(x["worse"]))
            put("Card%sComposeVs%sBpct" % (T, rt), pct(x["bytes_rel_pct_mean"]))
            put("Card%sComposeVs%sBsign" % (T, rt),
                "fewer" if x["bytes_rel_pct_mean"] < 0 else "more")
        put("Card%sComposeBelowBest" % T, str(len(F["below_best"])))
        if F.get("large_vs_card_mean") is not None:
            put("Card%sComposeLargeVsCardD" % T, ("$%+.3f$" % F["large_vs_card_mean"]))
    for tag, c in J["classifier"].items():
        T = TAG[tag]
        if c.get("breaks"):
            put("Card%sBreaks" % T, "{:,}".format(c["breaks"]).replace(",", "{,}"))
            for k, n in (("precision_topology", "PrecTopo"), ("recall_topology", "RecTopo"),
                         ("precision_transient", "PrecTrans"), ("accuracy", "Acc")):
                if c[k] is not None:
                    put("Card%s%s" % (T, n), dec(c[k], 2))
            if c["departed_share"] is not None:
                put("Card%sDepartedPct" % T, "%.1f" % (100 * c["departed_share"]))
    put("CardNconds", str(sum(F["conditions"] for F in J["families"].values())))
    put("CardNruns", "{:,}".format(sum(J["runs"].values())).replace(",", "{,}"))
    L = ["%% generated by analysis/make_card_tables.py -- do not edit"]
    for k in sorted(M):
        L.append(B + "newcommand{" + B + "%s}{%s}" % (k, M[k]))
    (TAB / "card_numbers.tex").write_text(NL.join(L) + NL, encoding="utf-8")
    print("card_numbers.tex: %d macros" % len(M))


if __name__ == "__main__":
    main()
