"""Generate every numerical table in the manuscript from the run records.

Writes paper/tables/*.tex and
analysis_out/q1_tables.json (every number, for checking prose against tables).
No table in the manuscript is typed by hand.

Run:  python analysis/make_q1_tables.py
"""

import json
import statistics as st

from q1_common import (ABLATIONS, POLICIES, REF, ROOT, boot, conditions, fmt_p, load,
                       mean_of, paired, sign_p, val)

TAB = ROOT / "paper" / "tables"
OUT = ROOT / "analysis_out" / "q1_tables.json"
B = chr(92)
NL = chr(10)
# Display names are conceptual; the implementation labels (RREP-RESET, SCR, TIME-BUCKET,
# PERSISTENT-BACKOFF, SCR-2) remain the keys in the run records and are mapped in Table 2.
LABEL = {"RREP-RESET": "Route-level", "TIME-BUCKET": "Clock", "SCR": "Service-level",
         "PERSISTENT-BACKOFF": "Service-level + backoff", "AODV-STOCK": "Stock AODV",
         "SCR2": "Service-level, no gate"}
ABL_LABEL = {"NO-PROBE": "no escape path", "ONE-BLOCK": "one block ($K=1$)",
             "NO-DEADLINE": "deadline ignored", "NO-NODE-CAP": "no node cap",
             "RESET-ESCALATION": "reach reset on acquisition"}


def write(name, lines):
    TAB.mkdir(parents=True, exist_ok=True)
    (TAB / name).write_text("%% generated by analysis/make_q1_tables.py -- do not edit" + NL
                            + NL.join(lines) + NL, encoding="utf-8")


def f3(x):
    return ("$%+.3f$" % x).replace("+", "{+}") if x is not None else "--"


def ci(lo, hi):
    return "[$%+.3f$, $%+.3f$]" % (lo, hi)


def sample_size_rule():
    """Cells failing the registered rule, from analyze_campaign.py's own output."""
    import re as _re
    res = {}
    import subprocess
    import sys
    for tag, f, camp in (("C1", "c1_timely_pdr.txt", "c1_outage"), ("C4", "c4_timely_pdr.txt", "c4_scaling"),
                         ("S8", "stage8_timely_pdr.txt", "stage8_campaign")):
        path = ROOT / "analysis_out" / f
        if not path.exists():
            # regenerate from the run records with the campaign analysis that defines the rule
            out = subprocess.run([sys.executable, str(ROOT / "analysis" / "analyze_campaign.py"),
                                  "--campaign", camp, "--metric", "timely_pdr"],
                                 capture_output=True, text=True, cwd=str(ROOT)).stdout
            path.parent.mkdir(exist_ok=True)
            path.write_text(out)
        lines = [l for l in path.read_text(errors="replace").splitlines()
                 if _re.search(r" (None|10|20|30)$", l)]
        res[tag] = {"cells": len(lines), "fail": sum(1 for l in lines if l.endswith(" None"))}
    return res


def write_numbers(J):
    """One LaTeX macro per number quoted in the prose (manuscript/tables/numbers.tex)."""
    M = {}

    def put(name, value):
        M[name] = value

    def pct(x):
        return "%.0f" % abs(x)

    def dec(x, n=3):
        return ("%." + str(n) + "f") % x

    def signed(x, n=3):
        return ("$%+." + str(n) + "f$") % x

    o = J["ordering"]
    put("NumConds", str(sum(v["conditions"] for v in o.values())))
    put("FullOrder", str(sum(v["full_order"] for v in o.values())))
    put("FullOrderCfour", str(o["C4"]["full_order"]))
    put("RRgtTB", str(sum(v["rrep_gt_tb"] for v in o.values())))
    a = J["absolute"]
    for tag, T in (("C1", "Cone"), ("C4", "Cfour"), ("S8", "Seight")):
        for alg, A in (("AODV-STOCK", "Stock"), ("RREP-RESET", "RR"), ("TIME-BUCKET", "TB"),
                       ("SCR", "SCR"), ("PERSISTENT-BACKOFF", "PB")):
            put("%s%sT" % (T, A), dec(a["%s %s" % (tag, alg)]["timely"]))
            put("%s%sB" % (T, A), dec(a["%s %s" % (tag, alg)]["bytes_per_pkt"], 1))
    r = J["relative_vs_stock"]
    put("ConeRRTpct", pct(r["C1 RREP-RESET"]["timely_rel_pct"]))
    put("ConeRRBpct", pct(r["C1 RREP-RESET"]["bytes_rel_pct"]))
    put("ConeSCRTpct", pct(r["C1 SCR"]["timely_rel_pct"]))
    put("CfourRRTpct", pct(r["C4 RREP-RESET"]["timely_rel_pct"]))
    put("CfourRRBpct", pct(r["C4 RREP-RESET"]["bytes_rel_pct"]))
    put("CfourPBTpct", pct(r["C4 PERSISTENT-BACKOFF"]["timely_rel_pct"]))
    put("CfourPBBpct", pct(r["C4 PERSISTENT-BACKOFF"]["bytes_rel_pct"]))
    h = J["c1_rr_by_condition"]
    put("ConeRRhealthyPct", pct(h["healthy/0"]))
    put("ConeRRminPct", pct(min(h.values())))
    put("ConeRRmaxPct", pct(max(h.values())))
    f = J["frequency_vs_bytes"]
    put("ConeSCROrigPct", pct(f["C1 SCR"]["orig_pct"]))
    put("ConeSCRBytesPct", pct(f["C1 SCR"]["bytes_pct"]))
    put("SeightRROrigPct", "%.1f" % abs(f["S8 RREP-RESET"]["orig_pct"]))
    put("SeightRRBytesPct", "%.1f" % abs(f["S8 RREP-RESET"]["bytes_pct"]))
    put("CfourPBOrigPct", "%.1f" % abs(f["C4 PERSISTENT-BACKOFF"]["orig_pct"]))
    put("CfourPBBytesPct", "%.1f" % abs(f["C4 PERSISTENT-BACKOFF"]["bytes_pct"]))
    m = J["mechanism_c1"]["per_run"]
    put("SCRconf", "%.1f" % m["SCR"]["confirmations"])
    put("RRconf", "%.1f" % m["RREP-RESET"]["confirmations"])
    put("SCRdeny", "{:,.0f}".format(round(m["SCR"]["deny_no_allowance"], -2)).replace(",", "{,}"))
    put("RRdeny", "%.0f" % m["RREP-RESET"]["deny_no_allowance"])
    put("SCRtwoT", dec(m["SCR2"]["timely"]))
    put("SCRtwoB", dec(m["SCR2"]["bytes_per_pkt"], 1))
    put("SCRtwoBpct", pct(100 * (m["SCR2"]["bytes_per_pkt"] / m["AODV-STOCK"]["bytes_per_pkt"] - 1)))
    pp = J["mechanism_c1"]["paired"]
    x = pp["SCR2-SCR timely"]; put("SCRtwoVsSCR", dec(x["mean"])); put("SCRtwoVsSCRci", "[%s, %s]" % (dec(x["ci"][0]), dec(x["ci"][1])))
    x = pp["SCR2-AODV-STOCK timely"]; put("SCRtwoVsStock", dec(abs(x["mean"]))); put("SCRtwoVsStockci", "[$%s$, $%s$]" % (dec(x["ci"][0]), dec(x["ci"][1])))
    put("SCRtwoN", str(x["n"]))
    gap = a["C1 AODV-STOCK"]["timely"] - a["C1 SCR"]["timely"]
    put("SCRtwoRecoveredPct", pct(100 * pp["SCR2-SCR timely"]["mean"] / gap))
    nd = J["no_deadline_pooled"]
    put("NDn", str(nd["timely"]["n"]))
    put("NDlate", "%.0f" % abs(nd["late"]["mean"]))
    put("NDlateci", "%.0f--%.0f" % (abs(nd["late"]["ci"][1]), abs(nd["late"]["ci"][0])))
    put("NDconf", "%+.1f" % nd["service_confirmations"]["mean"])
    put("NDconfci", "[$%+.2f$, $%+.2f$]" % tuple(nd["service_confirmations"]["ci"]))
    put("NDtimely", "$%+.4f$" % nd["timely"]["mean"])
    put("NDtimelyci", "[$%+.4f$, $%+.4f$]" % tuple(nd["timely"]["ci"]))
    put("NDscrconf", "%.1f" % nd["scr_confirmations"])
    put("NDconfPct", "%.0f" % (100 * nd["service_confirmations"]["mean"] / nd["scr_confirmations"]))
    put("NDgapPct", "%.0f" % (100 * nd["timely"]["mean"] / abs(nd["scr_minus_stock"])))
    put("NDlatePerConf", "{:,.0f}".format(round(abs(nd["late"]["mean"]) / nd["service_confirmations"]["mean"], -1)).replace(",", "{,}"))
    ab = J["ablations"]
    put("AblConds", str(len(ab)))
    npv = [e["ablations"]["NO-PROBE"]["mean"] for e in ab]
    put("NoProbeMin", dec(abs(max(npv))))
    put("NoProbeMax", dec(abs(min(npv))))
    put("OtherBound", dec(max(e["widest_other_bound"] for e in ab)))
    ratios = [abs(e["scr_minus_stock"]) / e["widest_other_bound"] for e in ab]
    put("GapRatioMin", "%.0f" % min(ratios))
    put("GapRatioMax", "%.0f" % max(ratios))
    ex = J["ablation_exclusions"]
    cells = sum(len(e["ablations"]) - 1 for e in ab)
    put("OtherCells", str(cells))
    put("OtherIncl", str(cells - len(ex)))
    put("OtherExcl", str(len(ex)))
    put("OtherMaxEff", dec(max(abs(x["mean"]) for x in ex)) if ex else "0")
    low = min((e["rate"] for e in ab), key=float)
    exlow = [x for x in ex if x["rate"] == low]
    put("OtherExclLowLoad", str(len(exlow)))
    words = "zero one two three four five six seven eight nine ten".split()
    put("OtherExclW", words[len(ex)] if len(ex) <= 10 else str(len(ex)))
    put("OtherExclLowLoadW", words[len(exlow)] if len(exlow) <= 10 else str(len(exlow)))
    put("OtherExclLowLoadPos", str(sum(1 for x in exlow if x["mean"] > 0)))
    put("LowLoad", low)
    if exlow:
        put("LowLoadGapRatio", "%.0f" % min(abs(x["scr_minus_stock"]) / abs(x["mean"]) for x in exlow))
    rr = J["stage8_rrep_reset"]
    put("SeightRRmin", dec(abs(max(x["mean"] for x in rr))))
    put("SeightRRmax", dec(abs(min(x["mean"] for x in rr))))
    put("SeightRRexcl", str(sum(1 for x in rr if x["ci"][1] < 0 or x["ci"][0] > 0)))
    lo = [x for x in rr if x["rate"] == "5"][0]
    put("SeightRRlowload", dec(abs(lo["mean"])))
    worst = min(rr, key=lambda x: x["mean"])
    put("SeightRRworst", dec(abs(worst["mean"])))
    put("SeightRRworstSpeed", worst["speed"])
    hi = [x for x in rr if x["rate"] == "40"][0]
    put("SeightRRhighload", dec(abs(hi["mean"])))
    pw = J["pairwise"]
    put("RRgtSCRsig", str(pw["RREP-RESET>SCR"]["ci_above_zero"]))
    put("TBgtSCRsig", str(pw["TIME-BUCKET>SCR"]["ci_above_zero"]))
    put("SCRgtPBsig", str(pw["SCR>PERSISTENT-BACKOFF"]["ci_above_zero"]))
    put("RRgtTBsig", str(pw["RREP-RESET>TIME-BUCKET"]["ci_above_zero"]))
    put("TBgtRRsig", str(pw["RREP-RESET>TIME-BUCKET"]["ci_below_zero"]))
    for sp, name in (("1", "One"), ("5", "Five"), ("10", "Ten"), ("15", "Fifteen")):
        v = [x for x in rr if x["speed"] == sp and x["rate"] == "20" and x["flows"] == "8"][0]
        put("SeightRRspeed" + name, dec(abs(v["mean"])))
    for tag, T in (("C1", "Cone"), ("C4", "Cfour"), ("S8", "Seight")):
        put("%sSCRconf" % T, "%.1f" % J["scr_conf"][tag])
        o_ = J["ordering"][tag]["SCR"]["mean"]
        put("%sSCRdiff" % T, dec(abs(o_)))
        put("%sRRdiff" % T, dec(abs(J["ordering"][tag]["RREP-RESET"]["mean"])))
    rec = J["recovery"]
    for alg, A in (("AODV-STOCK", "Stock"), ("RREP-RESET", "RR"), ("TIME-BUCKET", "TB"),
                   ("SCR", "SCR"), ("PERSISTENT-BACKOFF", "PB")):
        put("Cens%s" % A, "%.0f" % (100 * rec["healthy/stagger=0"][alg]["censored_fraction"]))
        put("Epi%s" % A, "%.0f" % rec["healthy/stagger=0"][alg]["episodes_per_run"])
    dens = dict(J["density_rr"])
    for n, name in ((30, "DensThirty"), (60, "DensSixty"), (90, "DensNinety"), (120, "DensHundredTwenty")):
        put(name, dec(abs(dens[n])))
    ivr = {r["arm"]: r for r in J["interventions"]["rows"]}
    for arm, nm in (("NO-PROBE", "NoProbe"), ("ONE-BLOCK", "OneBlock"), ("NO-NODE-CAP", "NodeCap"),
                    ("RESET-ESCALATION", "ResetEsc"), ("NO-DEADLINE", "NoDeadline")):
        r = ivr[arm]
        put("Pool%s" % nm, ("$%+.3f$" % r["mean"]).replace("+", "{+}"))
        put("Pool%sci" % nm, "[$%+.3f$, $%+.3f$]" % tuple(r["ci"]))
    ref = J["interventions"]["scr_minus_stock"]
    put("SCRstockMob", dec(abs(ref["Mobility"]["mean"])))
    lg = J["evidence_lag"]
    for tag, T in (("C1", "Cone"), ("S8", "Seight")):
        e = lg[tag]["AODV-STOCK"]["ecdf_ms"]
        put("Lag%sStockMedAll" % T, "%.1f" % (e[100] / 1000))
        put("Lag%sStockNinety" % T, "%.0f" % (e[180] / 1000) if e[180] is not None else "--")
    for tag, T in (("C1", "Cone"), ("S8", "Seight")):
        for alg, A in (("AODV-STOCK", "Stock"), ("SCR", "SCR")):
            v = lg[tag][alg]
            put("Lag%s%sMed" % (T, A), "%.1f" % (v["lag_median_ms"] / 1000))
            put("Lag%s%sGtOne" % (T, A), pct(100 * v["lag_gt_1s_fraction"]))
            put("Lag%s%sNever" % (T, A), pct(100 * v["never_confirmable_fraction"]))
    re_ = J["rerr_vs_stock"]
    for tag, T in (("C1", "Cone"), ("C4", "Cfour"), ("S8", "Seight")):
        for alg, A in (("RREP-RESET", "RR"), ("SCR", "SCR")):
            put("%s%sRerrPct" % (T, A), pct(re_["%s %s" % (tag, alg)]["pooled_pct"]))
    put("ConeRRRerrMin", pct(re_["C1 RREP-RESET"]["max_pct"]))
    put("ConeRRRerrMax", pct(re_["C1 RREP-RESET"]["min_pct"]))
    put("NumRunsMain", "{:,}".format(J["runs"]["main"]).replace(",", "{,}"))
    put("NumRunsAll", "{:,}".format(J["runs"]["all"]).replace(",", "{,}"))
    put("SCRdenyPerConf", "{:,.0f}".format(round(m["SCR"]["deny_no_allowance"] / m["SCR"]["confirmations"], -2)).replace(",", "{,}"))
    s = J["sample_size_rule"]
    put("RuleFail", str(sum(v["fail"] for v in s.values())))
    put("RuleCells", str(sum(v["cells"] for v in s.values())))
    put("RuleFailCone", str(s["C1"]["fail"]))
    put("RuleCellsCone", str(s["C1"]["cells"]))
    L = ["%% One macro per number quoted in the manuscript prose. Regenerated from the",
         "%% run records by analysis/make_q1_tables.py; never edit by hand."]
    for k in sorted(M):
        L.append(B + "newcommand{" + B + "%s}{%s}" % (k, M[k]))
    (TAB / "numbers.tex").write_text(NL.join(L) + NL, encoding="utf-8")
    J["macros"] = M
    print("numbers.tex: %d macros" % len(M))


def main():
    J = {}
    camps = {"C1": load("c1_outage"), "C4": load("c4_scaling"), "S8": load("stage8_campaign")}

    # ---------- ordering: mean paired difference vs stock over conditions ----------
    ordering = {}
    for tag, rows in camps.items():
        conds = conditions(rows)
        per = {p: [] for p in POLICIES}
        full = 0
        for c in conds:
            m = [mean_of(rows, p, c) for p in POLICIES]
            if all(x is not None for x in m) and all(m[i] > m[i + 1] for i in range(3)):
                full += 1
            for p in POLICIES:
                d = paired(rows, p, REF, c)
                if d:
                    per[p].append(st.mean(d))
        ordering[tag] = {"conditions": len(conds), "full_order": full,
                         "rrep_gt_tb": sum(1 for c in conds
                                           if mean_of(rows, "RREP-RESET", c) > mean_of(rows, "TIME-BUCKET", c)),
                         **{p: {"mean": st.mean(v), "min": min(v), "max": max(v)} for p, v in per.items()}}
    J["ordering"] = ordering
    L = [B + "begin{tabular}{@{}lccc@{}}", B + "toprule",
         "Renewal policy & Bottleneck (%d) & Scaling (%d) & Mobility (%d) " % tuple(
             ordering[k]["conditions"] for k in ("C1", "C4", "S8")) + B + B, B + "midrule"]
    for p in POLICIES:
        cells = []
        for tag in ("C1", "C4", "S8"):
            o = ordering[tag][p]
            cells.append("%s {\\scriptsize[%s, %s]}" % (f3(o["mean"]), f3(o["min"]), f3(o["max"])))
        L.append("%s & %s %s" % (LABEL[p], " & ".join(cells), B + B))
    L += [B + "midrule",
          "Conditions with the full order & %d / %d & %d / %d & %d / %d %s" % (
              ordering["C1"]["full_order"], ordering["C1"]["conditions"],
              ordering["C4"]["full_order"], ordering["C4"]["conditions"],
              ordering["S8"]["full_order"], ordering["S8"]["conditions"], B + B),
          B + "bottomrule", B + "end{tabular}"]
    write("tab_ordering.tex", L)

    # ---------- absolute timely PDR and control bytes ----------
    ab = {}
    for tag, rows in camps.items():
        for alg in [REF] + POLICIES:
            t = [val(kv, "timely") for (a, c, s), kv in rows.items() if a == alg]
            b = [val(kv, "bytes_per_pkt") for (a, c, s), kv in rows.items() if a == alg]
            ab[(tag, alg)] = (st.mean(t), st.mean(b), len(t))
    J["absolute"] = {"%s %s" % k: {"timely": v[0], "bytes_per_pkt": v[1], "runs": v[2]} for k, v in ab.items()}
    L = [B + "begin{tabular}{@{}lcccccc@{}}", B + "toprule",
         " & " + B + "multicolumn{2}{c}{Bottleneck} & " + B + "multicolumn{2}{c}{Scaling} & "
         + B + "multicolumn{2}{c}{Mobility} " + B + B,
         B + "cmidrule(lr){2-3}" + B + "cmidrule(lr){4-5}" + B + "cmidrule(lr){6-7}",
         "Arm & PDR$_{" + B + "mathrm{t}}$ & B/pkt & PDR$_{" + B + "mathrm{t}}$ & B/pkt & PDR$_{"
         + B + "mathrm{t}}$ & B/pkt " + B + B, B + "midrule"]
    for alg in [REF] + POLICIES:
        cells = []
        for tag in ("C1", "C4", "S8"):
            t, b, _ = ab[(tag, alg)]
            cells += ["%.3f" % t, "%.1f" % b]
        L.append("%s & %s %s" % (LABEL[alg], " & ".join(cells), B + B))
    L += [B + "bottomrule", B + "end{tabular}"]
    write("tab_absolute.tex", L)

    # ---------- principal results by regime (main text) ----------
    L = [B + "begin{tabular}{@{}l" + "rrr" * 3 + "@{}}", B + "toprule",
         " & " + " & ".join(B + "multicolumn{3}{c}{%s (%d cond.)}" % (nm, ordering[tg]["conditions"])
                             for tg, nm in (("C1", "Bottleneck"), ("C4", "Scaling"), ("S8", "Mobility")))
         + " " + B + B,
         B + "cmidrule(lr){2-4}" + B + "cmidrule(lr){5-7}" + B + "cmidrule(lr){8-10}",
         "Policy" + (" & PDR$_{" + B + "mathrm{t}}$ & $" + B + "Delta$ & B/pkt") * 3 + " " + B + B,
         B + "midrule"]
    for alg in [REF] + POLICIES:
        cells = []
        for tag in ("C1", "C4", "S8"):
            t, b, _ = ab[(tag, alg)]
            d = "--" if alg == REF else f3(ordering[tag][alg]["mean"])
            cells += ["%.3f" % t, d, "%.1f" % b]
        L.append("%s & %s %s" % (LABEL[alg], " & ".join(cells), B + B))
    L += [B + "bottomrule", B + "end{tabular}"]
    write("tab_principal.tex", L)

    # ---------- relative changes quoted in prose ----------
    rel = {}
    for tag in ("C1", "C4", "S8"):
        st_t, st_b, _ = ab[(tag, REF)]
        for alg in POLICIES:
            t, b, _ = ab[(tag, alg)]
            rel["%s %s" % (tag, alg)] = {"timely_rel_pct": 100 * (t / st_t - 1),
                                         "bytes_rel_pct": 100 * (b / st_b - 1)}
    J["relative_vs_stock"] = rel

    # ---------- origination count vs channel bytes ----------
    fb = {}
    for tag, rows in camps.items():
        for alg in POLICIES:
            o = so = b = sb = 0.0
            for c in conditions(rows):
                for (a, cc, s), kv in rows.items():
                    if a == alg and cc == c and (REF, c, s) in rows:
                        r = rows[(REF, c, s)]
                        o += val(kv, "source_rreq_originated"); so += val(r, "source_rreq_originated")
                        b += val(kv, "ctrl_bytes_sent"); sb += val(r, "ctrl_bytes_sent")
            fb["%s %s" % (tag, alg)] = {"orig_pct": 100 * (o / so - 1), "bytes_pct": 100 * (b / sb - 1)}
    J["frequency_vs_bytes"] = fb

    # ---------- route-error messages relative to stock (paired sums) ----------
    re_ = {}
    for tag, rows in camps.items():
        for alg in POLICIES:
            per = []
            x = sx = 0.0
            for c in conditions(rows):
                a1 = sum(val(kv, "ctrl_rerr_sent") for (a, cc, s), kv in rows.items()
                         if a == alg and cc == c and (REF, c, s) in rows)
                a0 = sum(val(rows[(REF, c, s)], "ctrl_rerr_sent") for (a, cc, s) in rows
                         if a == alg and cc == c and (REF, c, s) in rows)
                per.append(100 * (a1 / a0 - 1))
                x += a1; sx += a0
            re_["%s %s" % (tag, alg)] = {"pooled_pct": 100 * (x / sx - 1), "min_pct": min(per),
                                         "max_pct": max(per)}
    J["rerr_vs_stock"] = re_
    J["evidence_lag"] = json.loads((ROOT / "analysis_out" / "evidence_lag.json").read_text())["lag"]
    J["runs"] = {"main": sum(len(r) for r in camps.values())}
    J["runs"]["all"] = J["runs"]["main"] + len(load("c1_scr2_supplement")) + len(load("stage9_ablation_sweep"))
    L = [B + "begin{tabular}{@{}lcccccc@{}}", B + "toprule",
         " & " + B + "multicolumn{2}{c}{Bottleneck} & " + B + "multicolumn{2}{c}{Scaling} & "
         + B + "multicolumn{2}{c}{Mobility} " + B + B,
         B + "cmidrule(lr){2-3}" + B + "cmidrule(lr){4-5}" + B + "cmidrule(lr){6-7}",
         "Policy & orig. & bytes & orig. & bytes & orig. & bytes " + B + B, B + "midrule"]
    for alg in POLICIES:
        cells = []
        for tag in ("C1", "C4", "S8"):
            v = fb["%s %s" % (tag, alg)]
            cells += ["$%+.1f$" % v["orig_pct"], "$%+.1f$" % v["bytes_pct"]]
        L.append("%s & %s %s" % (LABEL[alg], " & ".join(cells), B + B))
    L += [B + "bottomrule", B + "end{tabular}"]
    write("tab_frequency.tex", L)

    # ---------- mechanism: C1 per-run counters, incl. SCR-2 ----------
    c1 = {**camps["C1"], **load("c1_scr2_supplement")}
    mech = {}
    for alg in (REF, "RREP-RESET", "SCR", "SCR2"):
        rs = [kv for (a, c, s), kv in c1.items() if a == alg]

        def mm(k, rs=rs):
            v = [float(kv[k]) for kv in rs if kv.get(k) not in (None, "")]
            return st.mean(v) if v else None
        mech[alg] = {"runs": len(rs),
                     "timely": st.mean(val(kv, "timely") for kv in rs),
                     "bytes_per_pkt": st.mean(val(kv, "bytes_per_pkt") for kv in rs),
                     "originations": mm("source_rreq_originated"),
                     "confirmations": mm("service_confirmations"),
                     "deny_no_allowance": mm("deny_no_allowance"),
                     "rerr_messages": mm("ctrl_rerr_sent")}
    pairs = {}
    for a, b_ in (("SCR2", "SCR"), ("SCR2", REF), ("RREP-RESET", "SCR")):
        for m in ("timely", "bytes_per_pkt"):
            d = [x for c in conditions(camps["C1"]) for x in paired(c1, a, b_, c, m)]
            lo, hi = boot(d)
            pairs["%s-%s %s" % (a, b_, m)] = {"n": len(d), "mean": st.mean(d), "ci": [lo, hi],
                                              "sign_p": sign_p(d)}
    J["mechanism_c1"] = {"per_run": mech, "paired": pairs}

    def n0(x):
        return "--" if x is None else "{:,.0f}".format(x).replace(",", "{,}")
    L = [B + "begin{tabular}{@{}lcccc@{}}", B + "toprule",
         "Per 300\\,s run, all flows & Stock AODV & Route-level & Service-level & Service-level, no gate " + B + B, B + "midrule",
         "Timely PDR & " + " & ".join("%.3f" % mech[a]["timely"] for a in (REF, "RREP-RESET", "SCR", "SCR2")) + " " + B + B,
         "Control bytes per packet & " + " & ".join("%.1f" % mech[a]["bytes_per_pkt"] for a in (REF, "RREP-RESET", "SCR", "SCR2")) + " " + B + B,
         "Source route requests & " + " & ".join(n0(mech[a]["originations"]) for a in (REF, "RREP-RESET", "SCR", "SCR2")) + " " + B + B,
         "Service confirmations & -- & " + " & ".join("%.1f" % mech[a]["confirmations"] for a in ("RREP-RESET", "SCR", "SCR2")) + " " + B + B,
         "Requests denied, allowance empty & -- & " + " & ".join(n0(mech[a]["deny_no_allowance"]) for a in ("RREP-RESET", "SCR")) + " & -- " + B + B,
         "Route-error messages sent & " + " & ".join(n0(mech[a]["rerr_messages"]) for a in (REF, "RREP-RESET", "SCR", "SCR2")) + " " + B + B,
         B + "bottomrule", B + "end{tabular}"]
    write("tab_mechanism.tex", L)

    # ---------- recovery (C1), from analysis/recovery_table.py ----------
    rec = json.loads((ROOT / "analysis_out" / "recovery_c1_rev5.json").read_text())["table"]
    J["recovery"] = rec
    L = [B + "begin{tabular}{@{}lcccc@{}}", B + "toprule",
         " & " + B + "multicolumn{3}{c}{Healthy condition (10 runs per arm)} & All six (60 runs) " + B + B,
         B + "cmidrule(lr){2-4}" + B + "cmidrule(lr){5-5}",
         "Arm & episodes/run & censored & median $T_{" + B + "mathrm{true}}$ & censored " + B + B, B + "midrule"]
    for alg in [REF] + POLICIES:
        h, a = rec["healthy/stagger=0"][alg], rec["ALL"][alg]
        L.append("%s & %.1f & %.1f" % (LABEL[alg], h["episodes_per_run"], 100 * h["censored_fraction"])
                 + B + "%% & " + "{:,}".format(h["median_true_ms_observed"]).replace(",", "{,}")
                 + B + ",ms & %.1f" % (100 * a["censored_fraction"]) + B + "%% " + B + B)
    L += [B + "bottomrule", B + "end{tabular}"]
    write("tab_recovery.tex", "\n".join(L).replace("%%", "%").split("\n"))

    # ---------- Stage 8 RREP-RESET vs stock per condition ----------
    s8 = camps["S8"]
    rr = []
    for c in conditions(s8):
        d = paired(s8, "RREP-RESET", REF, c)
        lo, hi = boot(d)
        rr.append({"speed": c[0], "rate": c[1], "flows": c[2], "n": len(d), "mean": st.mean(d),
                   "ci": [lo, hi], "sign_p": sign_p(d)})
    J["stage8_rrep_reset"] = rr
    L = [B + "begin{tabular}{@{}cccccc@{}}", B + "toprule",
         "Speed (m/s) & Load (pkt/s) & Flows & $n$ & $" + B + "Delta$ PDR$_{" + B + "mathrm{t}}$ & 95" + B + "% CI " + B + B,
         B + "midrule"]
    for r in rr:
        L.append("%s & %s & %s & %d & %s & %s %s" % (r["speed"], r["rate"], r["flows"], r["n"],
                                                     f3(r["mean"]), ci(*r["ci"]), B + B))
    L += [B + "bottomrule", B + "end{tabular}"]
    write("tab_stage8_rrep.tex", L)

    # ---------- ablations vs SCR in every condition with complete ablation data ----------
    s9 = load("stage9_ablation_sweep")
    abl_rows = {**s8, **s9}
    abl = []
    for c in conditions(abl_rows):
        entry = {"speed": c[0], "rate": c[1], "flows": c[2], "ablations": {}}
        ok = True
        for x in ABLATIONS:
            d = paired(abl_rows, x, "SCR", c)
            if len(d) < 30:
                ok = False
                break
            lo, hi = boot(d)
            entry["ablations"][x] = {"n": len(d), "mean": st.mean(d), "ci": [lo, hi], "sign_p": sign_p(d)}
        if not ok:
            continue
        g = paired(s8, "SCR", REF, c)
        entry["scr_minus_stock"] = st.mean(g)
        entry["widest_other_bound"] = max(max(abs(v["ci"][0]), abs(v["ci"][1]))
                                          for k, v in entry["ablations"].items() if k != "NO-PROBE")
        abl.append(entry)
    J["ablations"] = abl
    L = [B + "begin{tabular}{@{}ccccccc@{}}", B + "toprule",
         "Speed & Load & Flows & service-level $-$ stock & no escape path $-$ service-level & 95" + B + "% CI & other four: max $|" + B + "mathrm{CI}|$ " + B + B,
         B + "midrule"]
    for e in abl:
        npb = e["ablations"]["NO-PROBE"]
        L.append("%s & %s & %s & %s & %s & %s & %.3f %s" % (
            e["speed"], e["rate"], e["flows"], f3(e["scr_minus_stock"]), f3(npb["mean"]),
            ci(*npb["ci"]), e["widest_other_bound"], B + B))
    L += [B + "bottomrule", B + "end{tabular}"]
    write("tab_ablation.tex", L)

    # Full per-ablation table (supplementary material).
    L = [B + "begin{tabular}{@{}lccccc@{}}", B + "toprule",
         "Condition (m/s, pkt/s, flows) & Ablation & $n$ & $" + B + "Delta$ vs SCR & 95" + B + "% CI & sign $p$ " + B + B,
         B + "midrule"]
    for e in abl:
        for x in ABLATIONS:
            v = e["ablations"][x]
            L.append("%s, %s, %s & %s & %d & %s & %s & %s %s" % (
                e["speed"], e["rate"], e["flows"], ABL_LABEL[x], v["n"], f3(v["mean"]), ci(*v["ci"]),
                fmt_p(v["sign_p"]), B + B))
        L.append(B + "midrule")
    L[-1] = B + "bottomrule"
    L.append(B + "end{tabular}")
    write("tab_ablation_full.tex", L)

    # ---------- deadline relaxation, pooled over ablation conditions ----------
    nd = {}
    for m in ("timely", "late", "service_confirmations", "reports_accepted"):
        d = [x for e in abl for x in paired(abl_rows, "NO-DEADLINE", "SCR",
                                              (e["speed"], e["rate"], e["flows"]), m)]
        lo, hi = boot(d)
        nd[m] = {"n": len(d), "mean": st.mean(d), "ci": [lo, hi]}
    # Baselines for reading the pooled changes: SCR's own confirmations per run and its
    # deficit to stock AODV, both averaged over the same conditions (equal n per condition).
    nd["scr_confirmations"] = st.mean(mean_of(abl_rows, "SCR", (e["speed"], e["rate"], e["flows"]),
                                              "service_confirmations") for e in abl)
    nd["scr_minus_stock"] = st.mean(e["scr_minus_stock"] for e in abl)
    J["no_deadline_pooled"] = nd

    # ---------- interventions on SCR, pooled paired effects (mechanism figure) ----------
    # Each row changes one thing about SCR and is paired by seed within its own
    # family; pooling is over that family's conditions only.
    def pooled(rows, a, b_, conds):
        d = [x for c in conds for x in paired(rows, a, b_, c)]
        lo, hi = boot(d)
        return {"n": len(d), "mean": st.mean(d), "ci": [lo, hi]}
    mob = [(e["speed"], e["rate"], e["flows"]) for e in abl]
    c1s = {**camps["C1"], **load("c1_scr2_supplement")}
    iv = []
    for grp, lab, fam, rows, a in (
            ("evidence rule relaxed", "deadline ignored", "Mobility", abl_rows, "NO-DEADLINE"),
            ("evidence rule relaxed", "one block ($K=1$)", "Mobility", abl_rows, "ONE-BLOCK"),
            ("dependency removed", "service feedback without gate", "Bottleneck", c1s, "SCR2"),
            ("escape path removed", "no probe ($" + B + "rho=0$)", "Mobility", abl_rows, "NO-PROBE"),
            ("other components", "no node cap", "Mobility", abl_rows, "NO-NODE-CAP"),
            ("other components", "reach reset on acquisition", "Mobility", abl_rows, "RESET-ESCALATION")):
        conds = conditions(camps["C1"]) if fam == "Bottleneck" else mob
        iv.append({"group": grp, "label": lab, "family": fam, "arm": a, **pooled(rows, a, "SCR", conds)})
    ref = {"Bottleneck": pooled(camps["C1"], "SCR", REF, conditions(camps["C1"])),
           "Mobility": pooled(s8, "SCR", REF, mob)}
    J["interventions"] = {"rows": iv, "scr_minus_stock": ref}

    # Intervals of the four minor ablations that exclude zero.
    J["ablation_exclusions"] = [
        {"speed": e["speed"], "rate": e["rate"], "flows": e["flows"], "ablation": x,
         "mean": v["mean"], "ci": v["ci"], "scr_minus_stock": e["scr_minus_stock"]}
        for e in abl for x, v in e["ablations"].items()
        if x != "NO-PROBE" and (v["ci"][0] > 0 or v["ci"][1] < 0)]

    # ---------- per-condition paired tests behind the "all 26 conditions" claims ----------
    pw = {}
    for a_, b_ in (("RREP-RESET", "SCR"), ("TIME-BUCKET", "SCR"), ("SCR", "PERSISTENT-BACKOFF"),
                   ("RREP-RESET", "TIME-BUCKET")):
        res = []
        for tag, rows in camps.items():
            for c in conditions(rows):
                d = paired(rows, a_, b_, c)
                if d:
                    lo, hi = boot(d)
                    res.append({"campaign": tag, "condition": list(c), "mean": st.mean(d),
                                "ci": [lo, hi], "n": len(d)})
        pw["%s>%s" % (a_, b_)] = {
            "conditions": len(res),
            "positive_mean": sum(1 for r in res if r["mean"] > 0),
            "ci_above_zero": sum(1 for r in res if r["ci"][0] > 0),
            "ci_below_zero": sum(1 for r in res if r["ci"][1] < 0),
            "per_condition": res}
    J["pairwise"] = pw

    # ---------- supplementary: SCR-2 per C1 condition ----------
    s2 = []
    for c in conditions(camps["C1"]):
        d1 = paired(c1, "SCR2", "SCR", c)
        d2 = paired(c1, "SCR2", REF, c)
        if d1 and d2:
            s2.append((c, st.mean(d1), boot(d1), st.mean(d2), boot(d2), len(d1)))
    L = [B + "begin{tabular}{@{}lccccc@{}}", B + "toprule",
         "Bottleneck condition & $n$ & no gate $-$ service-level & 95" + B + "% CI & no gate $-$ stock & 95" + B + "% CI " + B + B,
         B + "midrule"]
    for c, m1, ci1, m2, ci2, n in s2:
        L.append("%s%s & %d & %s & %s & %s & %s %s" % (c[0], " (staggered)" if c[1] == "1" else "", n,
                                                     f3(m1), ci(*ci1), f3(m2), ci(*ci2), B + B))
    L += [B + "bottomrule", B + "end{tabular}"]
    write("tab_s_scr2.tex", L)

    # ---------- supplementary: native and external references ----------
    L = [B + "begin{tabular}{@{}lcccccc@{}}", B + "toprule",
         " & " + B + "multicolumn{2}{c}{Bottleneck} & " + B + "multicolumn{2}{c}{Scaling} & "
         + B + "multicolumn{2}{c}{Mobility} " + B + B,
         B + "cmidrule(lr){2-3}" + B + "cmidrule(lr){4-5}" + B + "cmidrule(lr){6-7}",
         "Arm & PDR$_{" + B + "mathrm{t}}$ & B/pkt & PDR$_{" + B + "mathrm{t}}$ & B/pkt & PDR$_{"
         + B + "mathrm{t}}$ & B/pkt " + B + B, B + "midrule"]
    for alg in ("AODV-STOCK", "AODV-FB", "OLSR", "DSDV"):
        cells = []
        for tag in ("C1", "C4", "S8"):
            rows = camps[tag]
            t_ = [val(kv, "timely") for (a, c, s), kv in rows.items() if a == alg]
            b_ = [val(kv, "bytes_per_pkt") for (a, c, s), kv in rows.items() if a == alg]
            # ctrl_bytes_sent instruments AODV-family control packets only, so it
            # reads 0 for OLSR and DSDV. That is not their control cost: print n/a.
            bcell = "n/a" if alg in ("OLSR", "DSDV") else ("%.1f" % st.mean(b_) if b_ else "--")
            cells += (["%.3f" % st.mean(t_), bcell] if t_ else ["--", "--"])
        L.append("%s & %s %s" % (LABEL.get(alg, alg), " & ".join(cells), B + B))
    L += [B + "bottomrule", B + "end{tabular}"]
    write("tab_s_references.tex", L)

    J["density_rr"] = []
    c4 = camps["C4"]
    for c in conditions(c4):
        if c[1] == "700" and c[2] == "8" and c[3] == "512":
            J["density_rr"].append((int(float(c[0])), st.mean(paired(c4, "RREP-RESET", REF, c))))
    J["c1_rr_by_condition"] = {"/".join(c): 100 * (mean_of(camps["C1"], "RREP-RESET", c) /
                                                   mean_of(camps["C1"], REF, c) - 1)
                               for c in conditions(camps["C1"])}
    J["sample_size_rule"] = sample_size_rule()
    J["scr_conf"] = {tag: st.mean(float(kv["service_confirmations"]) for (a, c, s), kv in rows.items()
                                  if a == "SCR")
                     for tag, rows in camps.items()}
    write_numbers(J)
    OUT.write_text(json.dumps(J, indent=1, default=float))
    print("tables written to", TAB)
    for f in sorted(TAB.glob("*.tex")):
        print("  ", f.name)
    print("ablation conditions with complete data:", len(abl))
    print("ordering full:", {k: "%d/%d" % (v["full_order"], v["conditions"]) for k, v in ordering.items()})


if __name__ == "__main__":
    main()
